name: Android CI
on:
  push:
    paths:
      - '*.gradle.kts'
      - '*.properties'
      - app/**
  pull_request:
    paths:
      - '*.gradle.kts'
      - '*.properties'
      - app/**

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew clean assembleDebug
